global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  
  - job_name: 'omada-exporter'
    static_configs:
      - targets: ['omada-exporter:9202']

  - job_name: 'watchtower'
    scrape_interval: 5s
    metrics_path: /v1/metrics
    bearer_token: token
    static_configs:
      - targets: ['10.20.20.130:8888']
  
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']
