global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'omada-exporter'
    static_configs:
      - targets: ['omada-exporter:9202']

  - job_name: 'watchtower'
    scrape_interval: 5s
    metrics_path: /v1/metrics
    bearer_token: ${WATCHTOWER_TOKEN}
    static_configs:
      - targets:
        - watchtower:8080
        - pg.dns.puvvadi.net:8888
        - jellyfin.dns.puvvadi.net:8888

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']

  - job_name: 'pve'
    static_configs:
      - targets:
        - pve.local.puvvadi.net:443
        - pve-ms1.local.puvvadi.net:443
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['1']
      node: ['1']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus-pve-exporter:9221  # PVE exporter.
