---
version: "3"

services:
  librespeed:
    image: lscr.io/linuxserver/librespeed
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      # results dashboard password
      - PASSWORD=SuperSecurePassword
    volumes:
      - /home/kd/librespeed/config:/config
    ports:
      - 8880:80
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librespeed.entrypoints=http"
      - "traefik.http.routers.librespeed.rule=Host(`speed.local.puvvadi.net`)"
      - "traefik.http.middlewares.librespeed-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.librespeed.middlewares=pihole-https-redirect"
      - "traefik.http.routers.librespeed-secure.entrypoints=https"
      - "traefik.http.routers.librespeed-secure.rule=Host(`speed.local.puvvadi.net`)"
      - "traefik.http.routers.librespeed-secure.tls=true"
      - "traefik.http.routers.librespeed-secure.service=librespeed"
      - "traefik.http.services.librespeed.loadbalancer.server.port=80"
      - "traefik.http.services.librespeed.loadbalancer.server.scheme=http"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
