---

- hosts: all
  become: true

  tasks:
    - name: Run apt cache update & upgrade
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        state: latest
        autoclean: true
        upgrade: true
