---

- name: Make install.sh executable
  ansible.builtin.file:
    path: "{{ omada_dir }}/install.sh"
    mode: a+x

- name: Install Omada
  ansible.builtin.command: "./install.sh -y -n"
  args:
    chdir: "{{ omada_dir }}"
  register: omadainstall

- name: Omada install status
  ansible.builtin.debug:
    msg: "{{ omadainstall.stdout_lines }}"

- name: Make sure Omada is running.
  ansible.builtin.service:
    name: tpeap
    state: started
    enabled: true

- name: Omada install check
  ansible.builtin.command: which tpeap
  failed_when: false
  changed_when: false
  check_mode: false
  register: omada_done

- name: Omada install status
  ansible.builtin.debug:
    msg: "{{ omada_done.stdout_lines }}"

- name: Reboot
  ansible.builtin.reboot:
    post_reboot_delay: 30
  when: reboot_required.stat.exists

- name: Get my public IP
  community.general.ipify_facts:
  register: ip
