---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  # generate cloudflare token, more info at https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/
  cloudflare-token: cf-toke
