version: "3.8"
services:
  dockge:
    container_name: dockge
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /home/kd:/home/kd
    environment:
      - DOCKGE_STACKS_DIR=/home/kd
    user: kd
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockge.entrypoints=http"
      - "traefik.http.routers.dockge.rule=Host(`dockge.local.puvvadi.net`)"
      - "traefik.http.routers.dockge.middlewares=dockge-https-redirect"
      - "traefik.http.middlewares.dockge-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dockge-secure.entrypoints=https"
      - "traefik.http.routers.dockge.middlewares=default-headers@file"
      - "traefik.http.routers.dockge-secure.rule=Host(`dockge.local.puvvadi.net`)"
      - "traefik.http.routers.dockge-secure.tls=true"
      - "traefik.http.routers.dockge-secure.service=dockge"
      - "traefik.http.services.dockge.loadbalancer.server.port=5001"
      - "traefik.http.services.dockge.loadbalancer.server.scheme=http"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
