---
version: '3'

services:
  semaphore:
    container_name: semaphore
    image: semaphoreui/semaphore:latest
    restart: unless-stopped
    user: root
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: pg.dns.puvvadi.net
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY_ENCRYPTION}
      ANSIBLE_HOST_KEY_CHECKING: False
    networks:
      - proxy
    volumes:
      - /home/kd/semaphore/data:/etc/semaphore
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.semaphore.entrypoints=https"
      - "traefik.http.routers.semaphore.rule=Host(`ansible.local.puvvadi.net`)"
      - "traefik.http.routers.semaphore.middlewares=default-headers@file, https-redirectscheme@file"
      - "traefik.http.routers.semaphore.tls=true"
      - "traefik.http.routers.semaphore.service=semaphore"
      - "traefik.http.services.semaphore.loadbalancer.server.scheme=http"
      - "traefik.http.services.semaphore.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
